version: '3.8'
services:
  elasticsearch:
    image: elasticsearch:8.12.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - /tank/elastic-sequence-lz4:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - airflow-net

  kibana:
    image: kibana:8.12.0
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - airflow-net

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - elasticsearch
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - airflow-net

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - airflow-net

  airflow-webserver:
    build: .
    command: webserver
    depends_on:
      - postgres
      - elasticsearch
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW_CONN_ELASTICSEARCH_DEFAULT=http://elasticsearch:9200
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
      - SPARK_HOME=/home/airflow/.local/lib/python3.8/site-packages/pyspark
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - /tank/csv:/opt/airflow/data
    ports:
      - "8080:8080"
    networks:
      - airflow-net

  airflow-scheduler:
    build: .
    command: scheduler
    depends_on:
      - airflow-webserver
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW_CONN_ELASTICSEARCH_DEFAULT=http://elasticsearch:9200
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - /tank/csv:/opt/airflow/data
    networks:
      - airflow-net

volumes:
  pg_data:
  elastic_data:
  grafana_data:

networks:
  airflow-net: